export enum TipoFalla {
  CON_CARGA_ACUMULADA = 'CON CARGA ACUMULADA',

  CON_RUIDO_Y_GOLPETEO = 'CON RUIDO Y GOLPETEO',

  CON_TEMPERATURA = 'CON TEMPERATURA',

  DE_IMPACTO_SIN_REVESTIMIENTO = 'DE IMPACTO SIN REVESTIMIENTO',

  DESBOCADO = 'DESBOCADO',

  DESGASTADO = 'DESGASTADO',

  DIAMETRO_INCORRECTO = 'DIÁMETRO INCORRECTO',

  INADECUADO = 'INADECUADO',

  INEXISTENTE = 'INEXISTENTE',

  TRABADO = 'TRABADO',
}
